### ISSUE TITLE
cli not working?

### ISSUE THREAD

**Issue by dpg5000** [omardelarosa/pitchfork-npm#3]
getting a "command not found" for a basic pitchfork artist search, after installing via npm.

**Comment by omardelarosa** [comment]
Ah i havent updated this in a while and need to. What version of node are
you running?

**Comment by dpg5000** [comment]
Thanks, this project of yours is right up my alley!

I'm on v4.4.5.   Would love to help in any way in maintaining this!

**Comment by omardelarosa** [comment]
@dpg5000 I just pushed up a new patch version `0.0.11`.  Try again and see if it works.  I tested with node 4.0 locally.

**Comment by dpg5000** [comment]
working great in 4.4.5.

I noticed that the flagless artist/album arguments weren't working, so I just submitted a PR.  Thanks!

**Comment by omardelarosa** [comment]
@dpg5000 Thanks!  Your PR is merged and version `0.0.12` is now published to npm: https://www.npmjs.com/package/pitchfork
