### ISSUE TITLE
cli not working

### ISSUE THREAD

**Issue by cvvvl** [omardelarosa/pitchfork-npm#8]
Firstly, thank you for this project!
I was trying to play with it, but after npm instalI I couldn't get cli to work.

I'm on v7.10.0 node.

<img width="506" alt="2017-05-23 13 44 07" src="https://cloud.githubusercontent.com/assets/28644840/26351042/69348212-3fbe-11e7-84c3-828efced551b.png">

**Comment by omardelarosa** [comment]
@cvvvl for the cli to work, you either need to try installing it globally using `npm install pitchfork -g` or the bin inside the node_modules dir `./node_modules/.bin/pitchfork` perhaps.

**Comment by cvvvl** [comment]
@omardelarosa My bad! Thank you, works perfectly :)
